version: "3.9"
services:
  jekyll:
    build:
      args:
        ALPINE_VERSION: "latest"
        JEKYLL_VERSION: "1.17.3"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "jekyll:dev"
    image: "jekyll:dev"
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/jekyll/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/jekyll/backup-volume
      
